name: perfmod CI

on: [push]

jobs:
  ci:
  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.14"]
        
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: ${{ github.ref }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Check package
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install check-manifest flake8
        check-manifest
    - name: flake8
      run: |
        flake8 .
    - name: Install dependencies
      run: |
        pip install -e .
#    - name: Run package creation
#      run: |
#        python -m pip install --user --upgrade build
#        python -m build
    - name: Run Unit Tests and generate coverage report
      run: |
        pip install coverage
        coverage run -m unittest discover
        coverage report -m
        coverage xml
        coverage html
#    - uses: actions/upload-artifact@v4
#      with:
#        path: ./wheelhouse/*.whl
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        verbose: false
    #- name: Archive code coverage html report
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: code-coverage-report
    #    path: htmlcov
    #- name: Archive package
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: imagedata
    #    path: src/dist
